---
apiVersion: v1
kind: Service
metadata:
  labels:
    category: database
    component: mongo
  name: mongo-svc
spec:
  ports:
  - name: connection-port
    port: 27017
    protocol: TCP
    targetPort: connection-port
  selector:
    app: mongo-svc
  sessionAffinity: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    category: database
    component: mongo
  name: mongo-svc-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-svc
      category: database
      component: mongo
  serviceName: mongo-svc
  template:
    metadata:
      labels:
        app: mongo-svc
        category: database
        component: mongo
    spec:
      containers:
      - args:
        - mongod
        - --storageEngine
        - wiredTiger
        - --smallfiles
        - --noprealloc
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: mongo:latest
        imagePullPolicy: Always
        name: mongo-svc
        ports:
        - containerPort: 27017
          name: connection-port
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gke-default
